apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-hermetic-example-test-branch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hermetic-example-test-branch
    app.kubernetes.io/part-of: go-hermetic-example-1
  name: go-hermetic-example-test-eigf
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-hermetic-example-test-branch
    weight: null
status: {}
