apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-hermetic-example-test-branch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-hermetic-example-test-branch
    app.kubernetes.io/part-of: go-hermetic-example-1
  name: go-hermetic-example-test-branch
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-hermetic-example-test-branch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-hermetic-example-test-branch
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/go-hermetic-example-1/go-hermetic-example-test-branch@sha256:6de903a52684bb727ac8942759ff84f4351451c5258f3a6ca1fbe58ceede6eb7
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
